version: '3.1'

services:
  db:
    image: postgres:9.6
    container_name: postgres-misis
    environment:
      POSTGRES_PASSWORD: 1111
    ports:
      - "5435:5432"
      - "8081:8080"

  fun-cart:
    image: misis-account
    container_name: misis-account
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    environment:
      PGHOST: localhost
      PGPORT: 5434
      PGNAME: fun-cart
      PGUSER: postgres
      PGPASS: 1111
    ports:
      - 8080:8080
